language: node_js
node_js:
- '0.10'
env:
- NODE_ENV=travis
services:
- mongodb
deploy:
  provider: opsworks
  access_key_id: AKIAIM2NCIV7UNEU3DXA
  secret_access_key:
    secure: bSYRnM4Y4JZKIpKTm66CXfe9ZtIpbRrFWYCUtO6c0k3r+zejnjoCiEoJNUBXG/ssAoKTwcd+QauX0UlQwI8Pg+gFXHEmy3cpuS8aAZsfHmS1N40Pn6S1xsp+WyIkxmPqr0kVuCDOis3yi0POtU5611aGP8ukBWbxxnGmCI7f2+E=
  app-id: fe1b9d65-6f9f-4a63-9054-660cd3901d2f
  on:
    repo: nghiank/ComOn
    branch: AWS_Deployment
